- name: Update NUC
  hosts: 127.0.0.1
  vars:
    ansible_python_interpreter: /usr/bin/python3.11
  connection: local
  become: yes
  tasks:
    - name: APT Package Updater
      apt:
        update_cache: yes
        upgrade: yes
