- name: Backup Flatnote
  hosts: ubuntu
  become: true
  tasks:
    - name: Create Flatnote backup archive and copy to Synology NAS
      shell: >
        tar czf /mnt/obsidian/flatnote/flatnote-backup-$(date +%F).tar.gz /mnt/Netbackup/configurations-backups/flatnote
