- name: Backup Flatnote
  hosts: ubuntu
  become: true
  tasks:
    - name: Create Flatnote backup archive
      shell: >
        tar czf /mnt/obsidian/flatnote/flatnote-backup-$(date +%F).tar.gz /mnt/obsidian/flatnote
   
    - name: Copy tarball to Google Drive
      shell: >
        cp /mnt/obsidian/flatnote/flatnote-backup*.tar.gz /mnt/NetBackup/configurations-backups/flatnote
      
