- name: Backup Flatnote
  hosts: ubuntu
  become: true
  tasks:
    - name: 
      ansible.builtin.stat:
        path: /mnt/Netbackup/configurations-backups/flatnote
      register: flatnote_backup_dir
  
    - name: Create Flatnote backup archive and copy to Synology NAS
      ansible.builtin.command: >
        tar czf /mnt/obsidian/flatnote/flatnote-backup-$(date +%F).tar.gz /mnt/Netbackup/configurations-backups/flatnote
      when: flatnote_backup_dir.stat.exists
      
