- hosts: "plex"
  become: yes
  tasks:
    - name: Check Nvidia Driver
      ansible.builtin.shell:
        nvidiasmi.sh
      register: nvidia_smi

    - name: Display output
      ansible.builtin.debug:
        var: nvidia_smi.stdout_lines
