- hosts: "plex"
  become: yes
  tasks:
    - name: Check nvidia driver, if not OK, then reinstall
      ansible.builtin.shell:
        /home/caradoc/nvidia-reboot.sh
      register: nvidia_reboot

    - name: Display output
      ansible.builtin.debug:
        var: nvidia_reboot.stdout_lines
