---
- name: Backup Proxmox Backup Server Configuration
  hosts: pbs
  become: true
  tasks:
    - name: Create PBS backup archive
      shell: >
        tar czf /root/backup/pbs-config-backup-$(date +%F).tar.gz /etc/proxmox-backup

    - name: Copy PBS backup to remote storage
      shell: >
        scp /root/backup/*.tar.gz root@192.168.5.249:/mnt/pve/Backups/configurations-backups/proxmox-bs

- name: Backup Proxmox VE Configuration
  hosts: pve
  become: true
  tasks:
    - name: Create PVE config archive
      shell: >
        tar czf /root/backup/pve-config-backup-$(date +%F).tar.gz /etc/pve /etc/network/interfaces /etc/hosts /etc/resolv.conf

    - name: Copy PVE backup to remote storage
      shell: >
        cp /root/backup/*.tar.gz /mnt/pve/Backups/configurations-backups/proxmox-ve

- name: Backup Flatnote
  hosts: ubuntu
  become: true
  tasks:
    - name: Copy Flatnote to remote storage
      shell: >
        cp /mnt/obsidian/flatnote/* /mnt/NetBackup/configurations-backups/flatnote
