- hosts: "nuc"
  become: yes
  tasks:
    - name: Update Portainer
      ansible.builtin.shell:
        /home/caracturus/portainerupdate.sh
      register: portainerupdate

    - name: Display output
      ansible.builtin.debug:
        var: portainerupdate.stdout_lines
